### ISSUE TITLE
Inconsistent and confusing naming

### ISSUE THREAD

**Issue by nchancel** [HPQC-LABS/quadratization-embeddings#4]
Names of the graphs seem somewhat inconsistent and can be very confusing, for instance we use the numeral '2' to both mean 'two' and 'to' in our names, this is particularly bad for 'All22Aux+1' where two adjacent 2's mean two different things. As another example, we use 'all to all' to refer to a k4 but refer to k5 and k6 by their graph names. We also need to make sure we use consistent naming for the same graph everywhere, I may be partially to blame for this, using the filenames rather than the ones we use in the paper.

**Comment by ndattani** [comment]
Fixed in latest commits. names such as "T" and "tripod" might change depending on whether or not we really want all reds in the centre, and namings  might be improved after Nike's second discussion with Nick Wormald, but at least the names are now consistent and not confusing in the way they previously were.
